import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Link from 'next/link'

const About = () => {
    return ( 
        <>
            <Head>
                <title>Hafiz</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar/>
            <div className='flex flex-col gap-5 pt-20 pb-10 text-white max-w-5xl m-auto text-sm md:text-base px-10 sm:px-20'>
                <h1 className='font-bold text-2xl'>Hello! I'm Hafiz,</h1>
                <p>I'm a student who is currently studying at Samudra Universty Department of Informatics based in Aceh, Indonesia 🌏.</p>
                <p>Currently interested on Web Developing, Graphic Artist and Animation. On this website, I am practicing and learning many stuff I interested on. 
                    May it looks bad, weird and junky. But hey, I'm on the process of learning something new here, and you're come along with my journey here 🚀. </p>
                <p>Outside of study, I play a lot of games like Team Fortress 2, The Sims 4, SA-MP, Minecraft, Don't Starve Together and also Mobile Legends.</p>
                <p>If you want getting closer with me, you can find me here:
                    <br/>📌 I'm <span className='border-b border-b-orange-400'>@hafizgv</span> on <Link className='hover:text-blue-400' href='https://www.facebook.com/hafiz.gv/' target='_blank'>Facebook</Link>, <Link className='hover:text-pink-400' href='https://www.instagram.com/hafizgv/' target='_blank'>Instagram</Link>, <Link href='https://github.com/hafizgv' target='_blank' className='hover:text-gray-400'>GitHub</Link>, <Link className='hover:text-cyan-400' href='https://www.linkedin.com/in/hafizgv/' target='_blank'>LinkedIn</Link> and <Link className='hover:text-red-400' href='https://www.youtube.com/@hafizgv' target='_blank'>Youtube</Link>
                    <br/>📌 May you want contact me from <Link className='border-b border-b-orange-400 hover:bg-orange-500' href='mailto:hafizgv@gmail.com' target='_blank'>email📧</Link>
                </p>
                <div className='bg-stone-700 rounded-sm h-1 w-full my-8'></div>
                <h1 className='font-bold text-2xl'>Career</h1>
                <div className='grid md:grid-cols-2 gap-10'>

                    <div>
                        <h2 className='font-semibold text-lg'>Mangayaro</h2>
                        <p>Staff
                            <br/>Sep 2020 - Now
                        </p>
                    </div>
                    
                    <div>
                        <h2 className='font-semibold text-lg'>Ngomik.net</h2>
                        <p>Volunteer
                            <br/>Aug 2020 - Now
                        </p>
                    </div>

                    <div>
                        <h2 className='font-semibold text-lg'>Ruangguru</h2>
                        <p>Frontend Engineer (Independent study)
                            <br/>Aug 2022 - Dec 2022
                        </p>
                    </div>
                </div>
                <div className='bg-stone-700 rounded-sm h-1 w-full my-8'></div>
                <footer className='text-center text-sm'>Copyright © 2023 HafizGv</footer>
            </div>
        </>
     );
}
 
export default About;